[package]
name = "procmonitor"
version = "0.3.2"
authors = ["katyamag <pupupu0701@gmail.com>"]
description = "Simple process monitor cli"
edition = "2018"

[dependencies]
procfs = "0.7.5"
clap = "2.33.0"
chrono = "0.4.15"
